### ISSUE TITLE
Github backend category config?

### ISSUE THREAD

**Issue by olblak** [chaoss/grimoirelab-sirmordred#137]
What's the goal of the category config in perceval? 
Should we either use 'pull_request', 'issue', or both? 

.mordred logs
````
perceval.errors.BackendError: ['pull_request', 'issue'] category not valid for GitHub
````

.mordred config
````
category = [pull_request, issue]
````

**Comment by acs** [comment]
`category` is used in perceval backends to defined what category of items to collect form a data source if there are several options.

In the case of github perceval backend:

http://perceval.readthedocs.io/en/latest/perceval.backends.core.html#module-perceval.backends.core.github

there are two possible options: `CATEGORIES = ['issue', 'pull_request']`

In you select `issue` github returns tickets and pull requests. If you select `pull_request` you collect only the pull requests from GitHub. @valeriocos am I right?

**Comment by valeriocos** [comment]
yes, @acs!
To give some more info, in GitHub every pull request is an issue, but not all issues are pull requests. @olblak, if you select the category **issue** you will get issues and pull requests, without pull request related data (e.g., review comments and requested reviewers). On the other hand, if you select the category **pull request**, you will get only pull requests and their related data.

Let us know if this answers your questions :)

**Comment by olblak** [comment]
@acs  @valeriocos  Thanks a lot for this complementary information.

**Comment by lukaszgryglicki** [comment]
How about git? I assume 'commit' should be used.
How about gerrit? review? quation?
How about other data sources?

In general, how can I configure sirmordred + kingarthur to fetch all possible categories?
- SirMordred requires to set `category` otherwise it panics `sirmordred/task_collection.py` at `ajson["tasks"][0]['category'] = backend_args['category']`.
- KingArthur: I cannot specify [category1, category2] - it panics too: `arthur/arthur.py` at `if not category or category.strip() == "":`
- If I specify them as a string comma separated `cat1,cat2` it simple doeasn't find anything (because it just uses category name `cat1,cat2` withour splitting this).

I just want to get all possible data from 3 datasources, how to do this?
```
[git]
(...)
category = commit

[github]
(...)
category = issue

[gerrit]
(...)
category = review
# category = question
```

in projects.json:
```
{
    "ONOS": {
        "git": [
            "github path"
        ],
        "github": [
            "github path"
        ],
        "gerrit": [
            "gerrit path"
        ]
    }
}
```

**Comment by valeriocos** [comment]
Hi @lukaszgryglicki ,
you can find the backend categories in the [doc](https://perceval.readthedocs.io/en/latest/perceval.backends.core.html). For instance, [question](https://perceval.readthedocs.io/en/latest/perceval.backends.core.html#perceval.backends.core.askbot.Askbot.CATEGORIES) is the category supported for Askbot, [review](https://perceval.readthedocs.io/en/latest/perceval.backends.core.html#perceval.backends.core.gerrit.Gerrit.CATEGORIES) for Gerrit and [issue and pull request](https://perceval.readthedocs.io/en/latest/perceval.backends.core.html#perceval.backends.core.github.GitHub.CATEGORIES) for Github.

In order to enable Arthur, you should set the param `arthur` to true in the `es_collection` section of the mordred `setup.cfg`. See example below:

```
[es_collection]
arthur = true  <-------------
arthur_url = http://127.0.0.1:8080
redis_url = redis://localhost/8
url = https://admin:admin@localhost:9200
```

If you want to get all possible data from git, github and gerrit, your `setup.cfg` and `projects.json` should look like:
**setup.cfg**
```
[git]
raw_index = test_git-raw
enriched_index = test_git
category = commit

[gerrit]
raw_index = test_gerrit-raw
enriched_index = test_gerrit
user = your-username
no-archive = true
category = review

[github:pulls]
raw_index = test_github-pulls-raw
enriched_index = test_github-pulls
api-token = a73226bd98be28fe9f40xd60ddbb01c1d0ac617e
sleep-for-rate = true
category = pull_request

[github:issues]
raw_index = test_github-issues-raw
enriched_index = test_github-issues
api-token = a73226bd98be28fe9f40xd60ddbb01c1d0ac617e
sleep-for-rate = true
category = issue
```
**projects.json**
```
{
    "ONOS": {
        "gerrit": [
            "gerrit path"
        ],
        "git": [
          "https://github.com/chaoss/grimoirelab-perceval"
        ],
        "github:pulls": [
            "https://github.com/chaoss/grimoirelab-perceval"
        ],
        "github:issues": [
            "https://github.com/chaoss/grimoirelab-perceval"
        ]
    }
}
```

**Comment by valeriocos** [comment]
you're welcome! yes, exactly!
Note that `cat1` and `cat2` are identifiers, so their values can be anything (e.g., datasource1:aaa, datasource1:bbb). However their values have to match the keys in the projects.json, for instance:
```
"datasource1:aaa": [
            "datasource URL"
],
"datasource1:bbb": [
            "datasource URL"
]
```

**Comment by jgbarah** [comment]
Hi @lukaszgryglicki @olblak, can we consider this as an answered question, and close it?

**Comment by lukaszgryglicki** [comment]
For me - yes.
