### ISSUE TITLE
Standard panels and menu must be updated automatically

### ISSUE THREAD

**Issue by sanacl** [chaoss/grimoirelab-sirmordred#162]
The current behavior of Mordred does not update an existing panel even if the flag `panels` is set to `true`. This is confusing because we have fresher available panels that our users are not seeing unless they wipe out the .kibana index. 

Mordred should allow user to:
* get fresh panels when they are released
* get the menu updated (as the menu is sometimes manually modified, overwriting it could be a pain the neck if so we must allow users to disable this)

My proposal is to decouple the current `panels` flag into `panels` and `menu`. When they are `true` the content will be replace based on the standard product, when they are false nor standard panels and menu will be updated.

**Comment by alpgarcia** [comment]
Related to https://github.com/chaoss/grimoirelab-kidash/pull/10

With that, panels could be updated if their version is newer than the current one in production.

Notice that panels depends on data, so panel update should depend on data version. Imho we need a smarter approach. Mordred should check data in the enriched index and decide when an index needs to be refreshed because there were updates in the enrichment.

With these two things, we could update panels automatically.

**Comment by acs** [comment]
I will focus in the panels automatic update. Enriching automatically indexes now is something that will need some elaborate logic and it is risky. I would prefer that operations does it in our current platform.

**Comment by sanacl** [comment]
Standard panels and menu are updated automatically, so I'm closing this issue.
