### ISSUE TITLE
Does a broken data source stop all data collection?

### ISSUE THREAD

**Issue by GeorgLink** [chaoss/grimoirelab-sirmordred#347]
I received the following question via email:

If we have 10 datasources and there is something wrong with the 5th one, does mordred skip that 5th one and proceed to pull from the 6th or will it just hang on 5th until it is fixed?

**Comment by valeriocos** [comment]
it is better if you redirect the person to the issue tracker. It avoids you to be in the middle.

**Comment by GeorgLink** [comment]
Good thinking. 😁
I posted the issue and directed the person here.

>

**Comment by valeriocos** [comment]
thanks :)

**Comment by fayazg** [comment]
Thanks for posting my question here @GeorgLink

**Comment by lukaszgryglicki** [comment]
Thanks guys, this is very important for us, there are projects with tens of hundreds of sources (using different backends) so it would be nice to do that in some sort of parallel, or give any source say 3 or 5 trials and if all fails then just proceed, anything that would fetch all data except failed source9s) instead of halting on faile done forever.

Arch: Sir Mordred + Arthurw + Arthurd with Redis/ElasticSearch.

Thanks a lot!

**Comment by sduenas** [comment]
If a source fails, it will be skipped and the other sources will be analyzed. You can use more `arthurw` instances to speed up data download from other sources.

**Comment by lukaszgryglicki** [comment]
Will it later check that failed data source again? Or skip it forever? Let's assume some data source failed due to some intermittent error on the data-source provider (like Jenkins/Jira/GitHub being down for a while), will it reattempt later or do we loose that particular data source forever (or at least until restarting `mordred`)?

**Comment by lukaszgryglicki** [comment]
So, to confirm, let's say we have a data-source loop say 100 elements, task 50 is broken.
It will go 1...49, then hit 50, tries `max_retries`times and let's say it fails all those trials. It will skip 50, then go 51, 52, .... 100. Then it sleeps for some time (3600s?) and then restarts all 100 tasks (to keep them updated forever). The question is will then 2nd run after sleep try to get 50th `max_retries` times, or due to the first loop, 50th won't be checked anymore?

If it will retry 50th then great, I just need to tweak `max_retry`, but in the latter case 50th is lost forever?

**Comment by sduenas** [comment]
Unfortunately, the 50th will not check anymore. This is done this way because if after those all tries it fails, probably means someone will need to go and check what's going on.

**Comment by lukaszgryglicki** [comment]
So this explains some issues we have, will https://github.com/chaoss/grimoirelab-kingarthur/issues/77 or https://github.com/chaoss/grimoirelab-kingarthur/issues/76 fix that? Or allow configuring how arthur should behave in such case? I can imagine that both approaches (remove forever and retry in next loops) could be useful.

**Comment by lukaszgryglicki** [comment]
Can you guys do something with it? I mean if any data source that fails `max_retries` times (say `max_retries` is 3) is removed then it *will* happen for every data source configured - this is just a matter of time. Say we have 100 totally correct GitHub data sources. One day GitHub is down for 1 hour. And Arthur is trying those 100 data sources, each of them 3 times, and because GitHub is down 20 repos got excluded forever before GitHub is up again. So we're left with 80 repos forever, after some time Slack is down, or Bugzilla is down, etc. After a long enough time, we will have nothing left.

**Comment by sduenas** [comment]
That's what we are working on. When a job fails, it will sleep until the next time it could run. If it keeps failing and it reaches `max_retries` it will be cancelled. The thing is you will be able to configure the next time this job will execute with the option `delay`. If you set it to run after a long period - 30 or 60 minutes - plus increasing `max_retries` value, would be more than enough to fix that problem.

Probably a lot of tasks will fail but they will run again. If they keep failing, probably there's something wrong and the user should check what's going on. If it is a server problem, the option to run those tasks again will come in handy.

**Comment by lukaszgryglicki** [comment]
An ideal solution, everybody would be able to tweak according to requirements, thanks.
