### ISSUE TITLE
Default (sample) aliases.json has a wrong structure. Dicts should be strings.

### ISSUE THREAD

**Issue by LedaMC-izubiaurre** [chaoss/grimoirelab-sirmordred#468]
The default [aliases.json](https://github.com/chaoss/grimoirelab-sirmordred/blob/master/aliases.json) file provides two lists of aliases (Raw and enriched) for each backend.

Currently aliases are dicts:
```
{ "enriched": [
    { "alias": "1st_ included_index" },
    { "alias": "2nd_included_index" },
    ...
  ]
}
```
They should be strings:
```
{ "enriched": [
  "1st_included_index",
  "2nd_included_index",
  ...
  ]
}
```
Working alias.json file provided within the grimoirelab/full docker container has lists of strings. Only the default file seems to be affected. Since it is expected to be taken as baseline for copy-pasting custom alias.json files, it needs corection.

Dicts cause faillures:
```
2020-05-22 19:25:39,627 - grimoire_elk.elk - ERROR - Error enriching ocean from gitlab (https://salsa.debian.org/freedombox-team/u-boot): unhashable type: 'dict'
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/grimoire_elk/elk.py", line 597, in enrich_backend
    elastic_enrich = get_elastic(url_enrich, enrich_index, clean, enrich_backend, es_enrich_aliases)
  File "/usr/local/lib/python3.5/dist-packages/grimoire_elk/utils.py", line 260, in get_elastic
    analyzers=analyzers, aliases=es_aliases)
  File "/usr/local/lib/python3.5/dist-packages/grimoire_elk/elastic.py", line 110, in __init__
    self.add_alias(alias)
  File "/usr/local/lib/python3.5/dist-packages/grimoire_elk/elastic.py", line 239, in add_alias
    if aliases and alias in aliases:
TypeError: unhashable type: 'dict'
```

**Comment by valeriocos** [comment]
Hi @LedaMC-izubiaurre , thank you for opening this issue!

It seems that you are using an oldest version of the aliases.json (https://github.com/chaoss/grimoirelab-sirmordred/commit/b6fa5962bfc5dcb7cc779a71586d91c92f3a7057#diff-b6d56075b6e9c4f45704f37afc64257e). I guess this may be due to the fact that the grimoirelab/full image isn't up to date with the latest release.

Can you try to replace the content of that file with https://github.com/chaoss/grimoirelab-sirmordred/blob/master/aliases.json?

If it is possible, you could use the [docker-compose](https://github.com/chaoss/grimoirelab/tree/master/docker-compose) solution, which always takes the latest image (https://github.com/chaoss/grimoirelab/blob/master/docker-compose/docker-compose.yml#L48)

Thanks

**Comment by LedaMC-izubiaurre** [comment]
ok, then. The container is outdated and aliases.json file has evolved. False positive. Closing the issue.

**Comment by valeriocos** [comment]
Thank you @LedaMC-izubiaurre for the quick feedback.
