### ISSUE TITLE
[Question] GrimoireLab deployed on Docker: Collection for git never finished, how to check status?

### ISSUE THREAD

**Issue by FabriceGaudin** [chaoss/grimoirelab-sirmordred#506]
## Context

I created a docker container following https://github.com/chaoss/grimoirelab/blob/master/docker/README.md and everything went perfectly. I can access the dashboard and after a long initialization, I have data from the github source (Issues and Pull requests). However, there's no data from the git source (commits).

Here's my projects.json file:
```json
{
    "platform": {
        "github": [
            "https://github.com/360Learning/platform"
        ],
        "git": [
            "https://github.com/360Learning/platform"
        ]
    }
}
```

In the log, I can see that the github source worked after a long init:
> Collection for github: starting...
> Collection for github: finished after 05:44:31 hours

I can also see it works without any error in the next loops (e.g. "Collection for github: finished after 00:00:03 hours").
But the git source never finished according to the log:
> Collection for git: starting...

## Question

**How can I check if there's an error or if it is still fetching the collection for git?** Ideally, I also would like to **check the progress** because the container already ran for several hours.

Thanks for your help! The dashboard looks very promising

**Comment by zhquan** [comment]
Hi @FabriceGaudin 

You can check the indexes and see if there are any items and if they are increasing.
```
GET _cat/indices
```
- collection: check raw indexes
- enrichment: check enriched indexes

It seems the repo https://github.com/360Learning/platform is private. Then you have to add your credentials on the projects.json as

```
{
    "platform": {
        "github": [
            "https://github.com/360Learning/platform"
        ],
        "git": [
            "https://user:token@github.com/360Learning/platform"
        ]
    }
}
```

There is no problem with `github` due to you added your token in the `setup.cfg`, but for `git` you have to add your credentials in the `projecs.json`

> How can I check if there's an error or if it is still fetching the collection for git?

Go to `all.log` and check if there is an error related to `git`.

I hope it helps you.

Best,
Quan

**Comment by FabriceGaudin** [comment]
@zhquan Thanks a lot for your reactivity and all the details! 🙏 
I missed the part stating that credentials are needed for `git`. I added them and now it's fixed. I checked with `GET _cat/indices` and I can see indexes getting created.

Thanks again, I'm closing this issue now 🙏
