### ISSUE TITLE
The optionality of `category` in the section `backend-name:tag`

### ISSUE THREAD

**Issue by xiao623** [chaoss/grimoirelab-sirmordred#512]
In `setup.cfg`, the `category` of the section `backend-name:tag` is not required.

if not set, it would have a default value in `perceval_backend.fetch`. But sometimes, we may make a mistake if there is no warning.
For example"
```
setup.cfg:

....

[github:repo]
raw_index = xxxxA
enriched_index = xxxxB
no-archive = true

```
I want to fetch items from github repos but finally i get the issue items.
Anyway, `category` would have a value (manual value or default value). I think it is better to use manual value so that users can ensure what they want because they need to set `category`.

So, I think it should add `category` in https://github.com/chaoss/grimoirelab-sirmordred/blob/cc6f81eb8573dee9202a35ea4449ede9c83856e6/sirmordred/config.py#L66 and require a manual value.

**Comment by zhquan** [comment]
Hi @xiao623,

First of all, thank you very much for opening the issue.

As you said the tag name is optional and you can give it any name (it does not affect the category). The important thing is to set the correct `category` (by default is `issue`). The tag name is just to help you to know what are you going to fetch.

For `github` backend we have several categories but for the rest of the backends we only have one category and that's why we decide to use a default value. Maybe for this specific case use a manual value makes sense but I think for the rest of them is better to use a default value.

Mordred uses `perceval` to fetch data https://perceval.readthedocs.io/en/latest/perceval.html

Best,
Quan
